################################################################################
# Assignment 3 - Data Visualization
################################################################################
#
# Kenzie M. Cooke
# kmc390@miami.edu
# 10/28/2025
#
#
################################################################################

# Load libraries
library(tidyverse)

# Load data from previous assignment
data <- read_rds("data/processed/all_data.rds")

# Convert date column to Date class
data <- data %>%
  mutate(date = as.Date(date, format =  "%m/%d/%y"))


# Calculate treatment statistics
data |>
  group_by(treatment) |>
  summarise(mean = mean(ta_av, na.rm = TRUE),
            pH = mean(p_h_pico, na.rm = TRUE),
            sd = sd(ta_av, na.rm = TRUE),
            n = sum(!is.na(ta_av)))

# Visualize the chemistry over time
ggplot(data,
       aes(x = date, y = ta_av, color = treatment)) +
  geom_jitter(width = 0.2) +
  geom_smooth() +
  theme_bw() +
  labs(title = "Treatment alkalinity over time",
       x = "Date",
       y = "Total alkalinity (umol/kg)",
       caption = "Data generated by Kenzie Cooke. September 2025")

# Transform data to assign "blank" content to samples that came from sumps
data_filtered <- data %>%
  filter(date >= as.Date("8/28/2025", format = "%m/%d/%Y")) %>%
  mutate(content = case_when(str_starts(string = vessel,
                                        pattern = "s") ~ "blank", # Replace NAs with blank in sump smaples
                             TRUE ~ content)) # otherwise keep original

# Visualize treatment statistics via boxplot
ggplot(data = data_filtered %>%
                filter(!vessel %in% c("sump_sw", "sump_esw")),  # Take out sumps afterall
       aes(x = treatment, y = ta_av, fill = treatment)) +
  geom_boxplot() +
  geom_point() +
  facet_wrap(~content) +
  theme_bw() +
  scale_fill_discrete(labels = c("ambient",
                                 "+ 300 umol",
                                 "+ 600 umol",
                                 "+ 900 umol",
                                 "source low",
                                 "source high")) +
  labs(title = "Treatment statistics summary",
       x = "Treatment",
       y = "Total alkalinity (umol/kg)",
       fill = "Treatment",
       content = c("Blank", "Coral"),
       subtitle = "faceted by vessel content",
       caption = "Data generated by Kenzie Cooke. September 2025")



